export enum ErrorEnum {
  // General Error Codes
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
  CONFLICT_ERROR = 'CONFLICT_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_INTEGRITY_ERROR = 'DATABASE_INTEGRITY_ERROR',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  TOKEN_GENERATION_ERROR = 'TOKEN_GENERATION_ERROR',
  TOKEN_INVALID = 'TOKEN_INVALID',
  JWT_VALIDATION_ERROR = 'JWT_VALIDATION_ERROR',
  TOKEN_REFRESH_NOT_FOUND = 'TOKEN_REFRESH_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  MEDIA_UPLOAD_ERROR = 'MEDIA_UPLOAD_ERROR',
  CHATBOT_NOT_FOUND = 'CHATBOT_NOT_FOUND',
  NODE_NOT_FOUND = 'NODE_NOT_FOUND',
  INVALID_NODE_TYPE = 'INVALID_NODE_TYPE',
  INVALID_NODE_CONFIGURATION = 'INVALID_NODE_CONFIGURATION',
  
  // Validation Error Codes - Phone Number
  INVALID_PHONE_NUMBER_FORMAT = 'INVALID_PHONE_NUMBER_FORMAT',
  INVALID_COUNTRY_CODE_FORMAT = 'INVALID_COUNTRY_CODE_FORMAT',
  COUNTRY_CODE_MISSING_PLUS = 'COUNTRY_CODE_MISSING_PLUS',
  COUNTRY_CODE_INVALID_DIGITS = 'COUNTRY_CODE_INVALID_DIGITS',
  
  // Validation Error Codes - Email
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  
  // Validation Error Codes - Password
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_MISSING_UPPERCASE = 'PASSWORD_MISSING_UPPERCASE',
  PASSWORD_MISSING_LOWERCASE = 'PASSWORD_MISSING_LOWERCASE',
  PASSWORD_MISSING_NUMBER = 'PASSWORD_MISSING_NUMBER',
  
  // Validation Error Codes - Name
  NAME_EMPTY = 'NAME_EMPTY',
  NAME_WHITESPACE_ONLY = 'NAME_WHITESPACE_ONLY',
  
  // Validation Error Codes - Media
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  FILE_SIZE_EXCEEDED = 'FILE_SIZE_EXCEEDED',
  
  // Validation Error Codes - CSV/File
  CSV_INVALID_FORMAT = 'CSV_INVALID_FORMAT',
  CSV_EMPTY_FILE = 'CSV_EMPTY_FILE',
  CSV_MISSING_REQUIRED_COLUMN = 'CSV_MISSING_REQUIRED_COLUMN',
  CSV_INVALID_ENCODING = 'CSV_INVALID_ENCODING',
  
  // Validation Error Codes - Recipient/Broadcast
  RECIPIENTS_NOT_LIST = 'RECIPIENTS_NOT_LIST',
  RECIPIENTS_EMPTY = 'RECIPIENTS_EMPTY',
  
  // Validation Error Codes - Interactive Message
  INTERACTIVE_BODY_TEXT_TOO_LONG = 'INTERACTIVE_BODY_TEXT_TOO_LONG',
  INTERACTIVE_HEADER_TEXT_TOO_LONG = 'INTERACTIVE_HEADER_TEXT_TOO_LONG',
  INTERACTIVE_FOOTER_TEXT_TOO_LONG = 'INTERACTIVE_FOOTER_TEXT_TOO_LONG',
  INTERACTIVE_BUTTON_TITLE_TOO_LONG = 'INTERACTIVE_BUTTON_TITLE_TOO_LONG',
  INTERACTIVE_BUTTON_ID_TOO_LONG = 'INTERACTIVE_BUTTON_ID_TOO_LONG',
  INTERACTIVE_TOO_MANY_BUTTONS = 'INTERACTIVE_TOO_MANY_BUTTONS',
  INTERACTIVE_MISSING_BUTTONS = 'INTERACTIVE_MISSING_BUTTONS',
  INTERACTIVE_TOO_MANY_LIST_SECTIONS = 'INTERACTIVE_TOO_MANY_LIST_SECTIONS',
  INTERACTIVE_TOO_MANY_LIST_ROWS = 'INTERACTIVE_TOO_MANY_LIST_ROWS',
  INTERACTIVE_LIST_ROW_TITLE_TOO_LONG = 'INTERACTIVE_LIST_ROW_TITLE_TOO_LONG',
  INTERACTIVE_LIST_ROW_DESCRIPTION_TOO_LONG = 'INTERACTIVE_LIST_ROW_DESCRIPTION_TOO_LONG',
  INTERACTIVE_LIST_BUTTON_TEXT_TOO_LONG = 'INTERACTIVE_LIST_BUTTON_TEXT_TOO_LONG',
  INTERACTIVE_LIST_ROW_ID_TOO_LONG = 'INTERACTIVE_LIST_ROW_ID_TOO_LONG',
  INTERACTIVE_MISSING_LIST_SECTIONS = 'INTERACTIVE_MISSING_LIST_SECTIONS',
  INTERACTIVE_MISSING_LIST_BUTTON = 'INTERACTIVE_MISSING_LIST_BUTTON',
  INTERACTIVE_INVALID_MESSAGE_STRUCTURE = 'INTERACTIVE_INVALID_MESSAGE_STRUCTURE',
  
  // Validation Error Codes - Time/Date
  TIMESTAMP_NOT_UTC = 'TIMESTAMP_NOT_UTC',
  DATETIME_MISSING_TIMEZONE = 'DATETIME_MISSING_TIMEZONE',
  
  // Validation Error Codes - Chatbot
  DUPLICATE_NODE_ID = 'DUPLICATE_NODE_ID',
  INVALID_NODE_POSITION = 'INVALID_NODE_POSITION',
  INVALID_LANGUAGE_CODE = 'INVALID_LANGUAGE_CODE',
  CHATBOT_NODE_ID_REQUIRED = 'CHATBOT_NODE_ID_REQUIRED',
  CHATBOT_NODE_TYPE_REQUIRED = 'CHATBOT_NODE_TYPE_REQUIRED',
  CHATBOT_NODE_BODY_REQUIRED = 'CHATBOT_NODE_BODY_REQUIRED',
  CHATBOT_NODE_POSITION_MISSING_COORDINATES = 'CHATBOT_NODE_POSITION_MISSING_COORDINATES',
  CHATBOT_NODE_POSITION_INVALID_COORDINATES = 'CHATBOT_NODE_POSITION_INVALID_COORDINATES',
  CHATBOT_INTERACTIVE_NODE_MISSING_BODY_BUTTON = 'CHATBOT_INTERACTIVE_NODE_MISSING_BODY_BUTTON',
  CHATBOT_MESSAGE_NODE_MISSING_BODY_MESSAGE = 'CHATBOT_MESSAGE_NODE_MISSING_BODY_MESSAGE',
  CHATBOT_MESSAGE_NODE_MISSING_CONTENT_ITEMS = 'CHATBOT_MESSAGE_NODE_MISSING_CONTENT_ITEMS',
  CHATBOT_QUESTION_NODE_MISSING_BODY_QUESTION = 'CHATBOT_QUESTION_NODE_MISSING_BODY_QUESTION',
  CHATBOT_MEDIA_HEADER_MISSING_MEDIA = 'CHATBOT_MEDIA_HEADER_MISSING_MEDIA',
  CHATBOT_NODE_INVALID_CONFIGURATION = 'CHATBOT_NODE_INVALID_CONFIGURATION',
  CHATBOT_NODE_INVALID_TYPE = 'CHATBOT_NODE_INVALID_TYPE',
  CHATBOT_MEDIA_UPLOAD_FAILED = 'CHATBOT_MEDIA_UPLOAD_FAILED',
  CHATBOT_MEDIA_DECODE_FAILED = 'CHATBOT_MEDIA_DECODE_FAILED',
  CHATBOT_MEDIA_INVALID_FORMAT = 'CHATBOT_MEDIA_INVALID_FORMAT',
  
  // Validation Error Codes - Send Message
  MESSAGE_BODY_EMPTY = 'MESSAGE_BODY_EMPTY',
  MESSAGE_BODY_TOO_LONG = 'MESSAGE_BODY_TOO_LONG',
  CONTEXT_MESSAGE_NOT_FOUND = 'CONTEXT_MESSAGE_NOT_FOUND',
  RECIPIENT_NUMBER_REQUIRED = 'RECIPIENT_NUMBER_REQUIRED',
  CLIENT_MESSAGE_ID_REQUIRED = 'CLIENT_MESSAGE_ID_REQUIRED',
  
  // Validation Error Codes - Get Conversations
  INVALID_PAGE_NUMBER = 'INVALID_PAGE_NUMBER',
  INVALID_LIMIT = 'INVALID_LIMIT',
  INVALID_SORT_BY = 'INVALID_SORT_BY',
  INVALID_STATUS_FILTER = 'INVALID_STATUS_FILTER',
  
  // Validation Error Codes - Get Messages
  CONVERSATION_ID_REQUIRED = 'CONVERSATION_ID_REQUIRED',
  INVALID_CONVERSATION_ID = 'INVALID_CONVERSATION_ID',
  CONVERSATION_NOT_ACCESSIBLE = 'CONVERSATION_NOT_ACCESSIBLE',
  INVALID_BEFORE_CREATED_AT = 'INVALID_BEFORE_CREATED_AT',
  INVALID_BEFORE_ID = 'INVALID_BEFORE_ID',
  INVALID_LIMIT_RANGE = 'INVALID_LIMIT_RANGE',
  
  // Validation Error Codes - Change Conversation Status
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  STATUS_ALREADY_SET = 'STATUS_ALREADY_SET',
  INVALID_STATUS_VALUE = 'INVALID_STATUS_VALUE',
  
  // Validation Error Codes - Change User Conversation Assign
  ASSIGNMENT_USER_NOT_FOUND = 'ASSIGNMENT_USER_NOT_FOUND',
  CONVERSATION_ALREADY_ASSIGNED = 'CONVERSATION_ALREADY_ASSIGNED',
  CANNOT_ASSIGN_TO_SELF = 'CANNOT_ASSIGN_TO_SELF',
  
  // Validation Error Codes - Create Template
  TEMPLATE_NAME_EMPTY = 'TEMPLATE_NAME_EMPTY',
  TEMPLATE_NAME_TOO_LONG = 'TEMPLATE_NAME_TOO_LONG',
  TEMPLATE_HEADER_TEXT_TOO_LONG = 'TEMPLATE_HEADER_TEXT_TOO_LONG',
  TEMPLATE_BODY_TEXT_TOO_LONG = 'TEMPLATE_BODY_TEXT_TOO_LONG',
  TEMPLATE_FOOTER_TEXT_TOO_LONG = 'TEMPLATE_FOOTER_TEXT_TOO_LONG',
  TEMPLATE_BUTTON_TEXT_TOO_LONG = 'TEMPLATE_BUTTON_TEXT_TOO_LONG',
  TEMPLATE_TOO_MANY_BUTTONS = 'TEMPLATE_TOO_MANY_BUTTONS',
  TEMPLATE_TOO_MANY_VARIABLES = 'TEMPLATE_TOO_MANY_VARIABLES',
  TEMPLATE_HEADER_MISSING_TEXT = 'TEMPLATE_HEADER_MISSING_TEXT',
  TEMPLATE_HEADER_MISSING_FORMAT = 'TEMPLATE_HEADER_MISSING_FORMAT',
  TEMPLATE_HEADER_MISSING_MEDIA = 'TEMPLATE_HEADER_MISSING_MEDIA',
  TEMPLATE_BODY_MISSING_TEXT = 'TEMPLATE_BODY_MISSING_TEXT',
  TEMPLATE_BODY_MISSING_EXAMPLE = 'TEMPLATE_BODY_MISSING_EXAMPLE',
  TEMPLATE_FOOTER_MISSING_TEXT = 'TEMPLATE_FOOTER_MISSING_TEXT',
  TEMPLATE_BUTTONS_MISSING = 'TEMPLATE_BUTTONS_MISSING',
  TEMPLATE_VARIABLE_MISSING_PARAM_NAME = 'TEMPLATE_VARIABLE_MISSING_PARAM_NAME',
  TEMPLATE_VARIABLE_MISSING_EXAMPLE = 'TEMPLATE_VARIABLE_MISSING_EXAMPLE',
  TEMPLATE_VARIABLES_MISMATCH = 'TEMPLATE_VARIABLES_MISMATCH',
  TEMPLATE_MARKETING_MISSING_BUTTON = 'TEMPLATE_MARKETING_MISSING_BUTTON',
  TEMPLATE_BUTTON_MISSING_TEXT = 'TEMPLATE_BUTTON_MISSING_TEXT',
  TEMPLATE_BUTTON_URL_MISSING = 'TEMPLATE_BUTTON_URL_MISSING',
  TEMPLATE_BUTTON_PHONE_MISSING = 'TEMPLATE_BUTTON_PHONE_MISSING',
  TEMPLATE_BUTTON_COPY_CODE_MISSING_EXAMPLE = 'TEMPLATE_BUTTON_COPY_CODE_MISSING_EXAMPLE',
  
  // Validation Error Codes - Create Broadcast
  BROADCAST_NAME_REQUIRED = 'BROADCAST_NAME_REQUIRED',
  BROADCAST_TEMPLATE_ID_REQUIRED = 'BROADCAST_TEMPLATE_ID_REQUIRED',
  BROADCAST_RECIPIENTS_EMPTY = 'BROADCAST_RECIPIENTS_EMPTY',
  BROADCAST_INVALID_SCHEDULED_TIME = 'BROADCAST_INVALID_SCHEDULED_TIME',
  BROADCAST_SCHEDULED_TIME_PAST = 'BROADCAST_SCHEDULED_TIME_PAST',
  BROADCAST_TEMPLATE_NOT_FOUND = 'BROADCAST_TEMPLATE_NOT_FOUND',
  BROADCAST_QUOTA_EXCEEDED = 'BROADCAST_QUOTA_EXCEEDED',
  
  // Validation Error Codes - Add Contact
  CONTACT_NAME_REQUIRED = 'CONTACT_NAME_REQUIRED',
  CONTACT_PHONE_REQUIRED = 'CONTACT_PHONE_REQUIRED',
  CONTACT_ALREADY_EXISTS = 'CONTACT_ALREADY_EXISTS',
  CONTACT_ATTRIBUTE_NOT_FOUND = 'CONTACT_ATTRIBUTE_NOT_FOUND',
  CONTACT_INVALID_PHONE = 'CONTACT_INVALID_PHONE',
  
  // Validation Error Codes - Create Chatbot
  CHATBOT_NAME_REQUIRED = 'CHATBOT_NAME_REQUIRED',
  CHATBOT_NAME_TOO_LONG = 'CHATBOT_NAME_TOO_LONG',
  CHATBOT_NAME_TOO_SHORT = 'CHATBOT_NAME_TOO_SHORT',
  CHATBOT_LANGUAGE_REQUIRED = 'CHATBOT_LANGUAGE_REQUIRED',
  CHATBOT_VERSION_REQUIRED = 'CHATBOT_VERSION_REQUIRED',
  CHATBOT_VERSION_INVALID = 'CHATBOT_VERSION_INVALID',
  CHATBOT_ALREADY_EXISTS = 'CHATBOT_ALREADY_EXISTS',
  
  // Validation Error Codes - Edit/Create User
  USER_FIRST_NAME_REQUIRED = 'USER_FIRST_NAME_REQUIRED',
  USER_LAST_NAME_REQUIRED = 'USER_LAST_NAME_REQUIRED',
  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS = 'USER_PHONE_ALREADY_EXISTS',
  USER_PASSWORD_REQUIRED = 'USER_PASSWORD_REQUIRED',
  USER_ROLE_IDS_REQUIRED = 'USER_ROLE_IDS_REQUIRED',
  USER_TEAM_IDS_REQUIRED = 'USER_TEAM_IDS_REQUIRED',
  USER_CANNOT_UPDATE_SELF = 'USER_CANNOT_UPDATE_SELF',
  USER_CANNOT_UPDATE_BASE_ADMIN = 'USER_CANNOT_UPDATE_BASE_ADMIN',
  USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
  
  // Validation Error Codes - Edit Business Profile
  BUSINESS_PROFILE_EMAIL_INVALID = 'BUSINESS_PROFILE_EMAIL_INVALID',
  BUSINESS_PROFILE_TOO_MANY_WEBSITES = 'BUSINESS_PROFILE_TOO_MANY_WEBSITES',
  BUSINESS_PROFILE_WEBSITE_TOO_LONG = 'BUSINESS_PROFILE_WEBSITE_TOO_LONG',
  BUSINESS_PROFILE_WEBSITE_INVALID_URL = 'BUSINESS_PROFILE_WEBSITE_INVALID_URL',
  BUSINESS_PROFILE_ABOUT_TOO_LONG = 'BUSINESS_PROFILE_ABOUT_TOO_LONG',
  BUSINESS_PROFILE_DESCRIPTION_TOO_LONG = 'BUSINESS_PROFILE_DESCRIPTION_TOO_LONG',
  BUSINESS_PROFILE_ADDRESS_TOO_LONG = 'BUSINESS_PROFILE_ADDRESS_TOO_LONG',
  BUSINESS_PROFILE_IMAGE_UPLOAD_FAILED = 'BUSINESS_PROFILE_IMAGE_UPLOAD_FAILED',
  
  // Validation Error Codes - Generic Field
  FIELD_REQUIRED = 'FIELD_REQUIRED',
  FIELD_INVALID_TYPE = 'FIELD_INVALID_TYPE',
  FIELD_INVALID_VALUE = 'FIELD_INVALID_VALUE',
  FIELD_TOO_LONG = 'FIELD_TOO_LONG',
  FIELD_TOO_SHORT = 'FIELD_TOO_SHORT',
}
