export class TemplateConstants {
  static readonly CATEGORIES = ['Marketing', 'Authentication', 'Utility'];

static readonly LANGUAGES = [
  { name: 'Afrikaans', code: 'af' },
  { name: 'Albanian', code: 'sq' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Arabic (Egypt)', code: 'ar_EG' },
  { name: 'Arabic (UAE)', code: 'ar_AE' },
  { name: 'Arabic (Lebanon)', code: 'ar_LB' },
  { name: 'Arabic (Morocco)', code: 'ar_MA' },
  { name: 'Arabic (Qatar)', code: 'ar_QA' },
  { name: 'Azerbaijani', code: 'az' },
  { name: 'Belarusian', code: 'be_BY' },
  { name: 'Bengali', code: 'bn' },
  { name: 'Bengali (India)', code: 'bn_IN' },
  { name: 'Bulgarian', code: 'bg' },
  { name: 'Catalan', code: 'ca' },
  { name: 'Chinese (China)', code: 'zh_CN' },
  { name: 'Chinese (Hong Kong)', code: 'zh_HK' },
  { name: 'Chinese (Taiwan)', code: 'zh_TW' },
  { name: 'Croatian', code: 'hr' },
  { name: 'Czech', code: 'cs' },
  { name: 'Danish', code: 'da' },
  { name: 'Dari', code: 'prs_AF' },
  { name: 'Dutch', code: 'nl' },
  { name: 'Dutch (Belgium)', code: 'nl_BE' },
  { name: 'English', code: 'en' },
  { name: 'English (UK)', code: 'en_GB' },
  { name: 'English (US)', code: 'en_US' },
  { name: 'English (UAE)', code: 'en_AE' },
  { name: 'English (Australia)', code: 'en_AU' },
  { name: 'English (Canada)', code: 'en_CA' },
  { name: 'English (Ghana)', code: 'en_GH' },
  { name: 'English (Ireland)', code: 'en_IE' },
  { name: 'English (India)', code: 'en_IN' },
  { name: 'English (Jamaica)', code: 'en_JM' },
  { name: 'English (Malaysia)', code: 'en_MY' },
  { name: 'English (New Zealand)', code: 'en_NZ' },
  { name: 'English (Qatar)', code: 'en_QA' },
  { name: 'English (Singapore)', code: 'en_SG' },
  { name: 'English (Uganda)', code: 'en_UG' },
  { name: 'English (South Africa)', code: 'en_ZA' },
  { name: 'Estonian', code: 'et' },
  { name: 'Filipino', code: 'fil' },
  { name: 'Finnish', code: 'fi' },
  { name: 'French', code: 'fr' },
  { name: 'French (Belgium)', code: 'fr_BE' },
  { name: 'French (Canada)', code: 'fr_CA' },
  { name: 'French (Switzerland)', code: 'fr_CH' },
  { name: 'French (Ivory Coast)', code: 'fr_CI' },
  { name: 'French (Morocco)', code: 'fr_MA' },
  { name: 'Georgian', code: 'ka' },
  { name: 'German', code: 'de' },
  { name: 'German (Austria)', code: 'de_AT' },
  { name: 'German (Switzerland)', code: 'de_CH' },
  { name: 'Greek', code: 'el' },
  { name: 'Gujarati', code: 'gu' },
  { name: 'Hausa', code: 'ha' },
  { name: 'Hebrew', code: 'he' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Indonesian', code: 'id' },
  { name: 'Irish', code: 'ga' },
  { name: 'Italian', code: 'it' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Kannada', code: 'kn' },
  { name: 'Kazakh', code: 'kk' },
  { name: 'Kinyarwanda', code: 'rw_RW' },
  { name: 'Korean', code: 'ko' },
  { name: 'Kyrgyz', code: 'ky_KG' },
  { name: 'Lao', code: 'lo' },
  { name: 'Latvian', code: 'lv' },
  { name: 'Lithuanian', code: 'lt' },
  { name: 'Macedonian', code: 'mk' },
  { name: 'Malay', code: 'ms' },
  { name: 'Malayalam', code: 'ml' },
  { name: 'Marathi', code: 'mr' },
  { name: 'Norwegian', code: 'nb' },
  { name: 'Pashto', code: 'ps_AF' },
  { name: 'Persian', code: 'fa' },
  { name: 'Polish', code: 'pl' },
  { name: 'Portuguese (Brazil)', code: 'pt_BR' },
  { name: 'Portuguese (Portugal)', code: 'pt_PT' },
  { name: 'Punjabi', code: 'pa' },
  { name: 'Romanian', code: 'ro' },
  { name: 'Russian', code: 'ru' },
  { name: 'Serbian', code: 'sr' },
  { name: 'Sinhala', code: 'si_LK' },
  { name: 'Slovak', code: 'sk' },
  { name: 'Slovenian', code: 'sl' },
  { name: 'Spanish', code: 'es' },
  { name: 'Spanish (Argentina)', code: 'es_AR' },
  { name: 'Spanish (Chile)', code: 'es_CL' },
  { name: 'Spanish (Colombia)', code: 'es_CO' },
  { name: 'Spanish (Costa Rica)', code: 'es_CR' },
  { name: 'Spanish (Dominican Republic)', code: 'es_DO' },
  { name: 'Spanish (Ecuador)', code: 'es_EC' },
  { name: 'Spanish (Honduras)', code: 'es_HN' },
  { name: 'Spanish (Mexico)', code: 'es_MX' },
  { name: 'Spanish (Panama)', code: 'es_PA' },
  { name: 'Spanish (Peru)', code: 'es_PE' },
  { name: 'Spanish (Spain)', code: 'es_ES' },
  { name: 'Spanish (Uruguay)', code: 'es_UY' },
  { name: 'Swahili', code: 'sw' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Tamil', code: 'ta' },
  { name: 'Telugu', code: 'te' },
  { name: 'Thai', code: 'th' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Uzbek', code: 'uz' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Zulu', code: 'zu' },
];

  static readonly MEDIA_TYPES = {
    NONE: 'None',
    TEXT: 'Text',
    IMAGE: 'Image',
    VIDEO: 'Video',
    DOCUMENT: 'Document'
  };

  static readonly MAX_FILE_SIZE = 16 * 1024 * 1024; // 16MB
  static readonly MAX_QUICK_REPLIES = 3;

  static readonly FILE_TYPES = {
    image: ['image/jpeg', 'image/png', 'image/gif'],
    video: ['video/mp4', 'video/3gpp'],
    document: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']
  };
}
